---
# tasks file for supervisor

- name: install supervisor
  apt:
    name: supervisor
    state: present
  notify: restart supervisor

- name: ensure /etc/supervisor/supervisor.d/ exists
  file:
    path: "/etc/supervisor/supervisord.d"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: create supervisor socket file
  raw: "mkdir -p /var/run/supervisor/ && touch /var/run/supervisor/supervisor.sock"

- name: generate supervisor config file
  template:
    src: supervisord.conf.j2
    dest: /etc/supervisor/supervisord.conf
  notify: restart supervisor

- name: enable supervisor service
  service:
    name: supervisor
    enabled: yes

- name: ensure that supervisor is started
  service:
    name: supervisor
    state: started

- name: generate supervisor config file for apache2 exists
  template:
    src: supervisor.conf.j2
    dest: /etc/apache2/conf.d/apps/supervisor.conf
  notify: restart apache

