# Generated by Django 2.1.1 on 2018-11-04 09:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.CharField(choices=[('open', 'open'), ('on_demand', 'on_demand'), ('restricted', 'restricted')], max_length=32, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bandpass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandpass', models.CharField(max_length=32)),
                ('bandpass_uid', models.CharField(max_length=32, unique=True)),
                ('spectral_band_type', models.CharField(choices=[('radio', 'radio'), ('millimeter', 'millimeter'), ('infrared', 'infrared'), ('optical', 'optical'), ('ultraviolet', 'ultraviolet'), ('xray', 'xray'), ('gammaray', 'gammaray')], max_length=64)),
                ('photometric_system', models.CharField(max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=32)),
                ('publisher', models.CharField(max_length=128)),
                ('publisher_did', models.CharField(max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=128)),
                ('facility_uid', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=64)),
                ('instrument_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('telescope', models.CharField(max_length=64)),
                ('camera', models.CharField(default=None, max_length=64, null=True)),
                ('spectroscope', models.CharField(default=None, max_length=64, null=True)),
                ('field_of_view', models.DecimalField(decimal_places=10, max_digits=20)),
                ('description', models.CharField(max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_hash', models.CharField(max_length=128, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observation.AccessRights')),
                ('dataid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observation.DataId')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observation.Facility')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observation.Instrument')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=128)),
                ('organisation_did', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.CharField(max_length=256)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bandpass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observation.Bandpass')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observation.Observation')),
            ],
        ),
        migrations.CreateModel(
            name='Spectroscopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.CharField(max_length=256)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observation.Observation')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=128)),
                ('catalogue', models.CharField(max_length=128)),
                ('catalogue_value', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128, null=True)),
                ('right_ascension', models.DecimalField(decimal_places=10, max_digits=20)),
                ('declination', models.DecimalField(decimal_places=10, max_digits=20)),
                ('target_class', models.CharField(max_length=128, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='target',
            unique_together={('catalogue', 'catalogue_value')},
        ),
        migrations.AddField(
            model_name='observation',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observation.Target'),
        ),
        migrations.AddField(
            model_name='dataid',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observation.Organisation'),
        ),
    ]
