# tasks file for java8

- name: add repo webupd8team
  apt_repository:
    repo: "{{ repo }}"
    update_cache: yes
    state: present

- name: accept oracle license
  debconf:
    name: "{{ java_package }}"
    question: "shared/accepted-oracle-license-v1-1"
    value: "true"
    vtype: "select"


- name: install java
  apt:
    name: "{{ java_package }}"
    state: present
